// Computes the circuit commitment every auction writes into ledger state at
// deploy: one hash over each auction circuit's verifier key (see
// circuit-commitment.mjs). The app only shows contracts carrying this value,
// so a contract with a similar layout cannot pass itself off as a MidBid
// auction.
import { writeFileSync } from 'node:fs';
import { circuitCommitmentOf, verifierKeys } from './circuit-commitment.mjs';

let circuitCommitment;
try {
  circuitCommitment = circuitCommitmentOf();
} catch (err) {
  console.error(err.message);
  process.exit(1);
}
const keys = verifierKeys();

// Emitted as an ES module rather than JSON so it loads identically under Node
// and Vite without import attributes.
const source = [
  '// GENERATED by scripts/provenance.js. Do not edit by hand.',
  `// circuitCommitment = one hash over verifier keys: ${keys.join(', ')}`,
  'export const PROVENANCE = {',
  `  circuitCommitment: '${circuitCommitment}',`,
  '};',
  '',
].join('\n');

writeFileSync('src/provenance.js', source);
console.log('circuitCommitment', circuitCommitment, `(${keys.join(', ')})`);
