// Reads the pilot register from Preprod and writes docs/USERS.md.
//
// The list is generated, never hand-maintained: every entry comes from contract
// state, and anyone can reproduce this file by running the script.
//
//   npm run users -- <pilotAddress>
import { writeFileSync } from 'node:fs';
import { ContractState } from '@midnight-ntwrk/compact-runtime';
import * as Pilot from '../managed/pilot/contract/index.js';

const INDEXER =
  process.env.VITE_INDEXER_URL ?? 'https://indexer.preprod.midnight.network/api/v4/graphql';
const ROLES = ['Tester', 'Builder', 'Seller', 'Bidder'];

const address = (process.argv[2] ?? process.env.VITE_PILOT_ADDRESS ?? '').toLowerCase();
if (!/^[0-9a-f]{64}$/.test(address)) {
  console.error('usage: npm run users -- <pilot contract address>');
  process.exit(2);
}

const gql = async (query, variables) => {
  const res = await fetch(INDEXER, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ query, variables }),
  });
  const body = await res.json();
  if (body.errors) throw new Error(JSON.stringify(body.errors).slice(0, 300));
  return body.data;
};

const data = await gql(
  `query($a: HexEncoded!) { contractAction(address: $a) {
     __typename address state transaction { hash block { height timestamp } } } }`,
  { a: address },
);
const action = data.contractAction;
if (!action) {
  console.error(`No pilot register at ${address} on Preprod.`);
  process.exit(1);
}

const ledger = Pilot.ledger(ContractState.deserialize(Buffer.from(action.state, 'hex')).data);
const members = [];
for (const [key, record] of ledger.entries) {
  try {
    const parsed = JSON.parse(record);
    if (typeof parsed?.address !== 'string') continue;
    members.push({
      address: parsed.address,
      handle: typeof parsed.handle === 'string' ? parsed.handle : '',
      joinedAt: Number(parsed.joinedAt) || 0,
      role: ROLES[Number(ledger.roles.lookup(key))] ?? 'Tester',
    });
  } catch {
    /* an entry anyone could have written; skip what does not parse */
  }
}
members.sort((a, b) => a.joinedAt - b.joinedAt);

const rows = members
  .map((m, i) => {
    const when = m.joinedAt ? new Date(m.joinedAt * 1000).toISOString().slice(0, 10) : '';
    return `| ${i + 1} | \`${m.address}\` | ${m.handle || '_none_'} | ${m.role} | ${when} |`;
  })
  .join('\n');

const doc = `# Preprod users

Generated by \`npm run users\`. Do not edit by hand.

Every row below is an entry in the MidBid pilot register, an opt-in contract on
Midnight Preprod. Each entry was written by a transaction the participant signed
and paid for with their own wallet.

- Pilot register: \`${address}\`
- Members: **${Number(ledger.joinedCount)}**
- Read at block ${action.transaction.block.height}, ${new Date(action.transaction.block.timestamp).toISOString()}

## Verify this list yourself

\`\`\`bash
npm run users -- ${address}
\`\`\`

The script reads contract state straight from the public indexer, so it does not
depend on anything MidBid hosts.

## What this list is, and is not

It **is** a list of people who chose to say publicly that they are testing MidBid
on Preprod.

It is **not** a list of bidders. MidBid cannot produce one: a bid carries a fresh
commitment, never a wallet. Nothing here says which auctions a member joined,
what they bid, or whether they bid at all. See [PRIVACY.md](PRIVACY.md).

The contract cannot check that a caller controls the address they submit. What it
can show is that each entry cost a real transaction from a funded Preprod wallet.

| # | Address | Handle | Role | Joined |
|---|---|---|---|---|
${rows || '| | _nobody has joined yet_ | | | |'}
`;

writeFileSync('docs/USERS.md', doc);
console.log(`docs/USERS.md written with ${members.length} member(s)`);
