// Public Midnight network configuration. Safe to commit: these are the same
// endpoints every Preprod participant uses. Each can be overridden at build time
// through the VITE_ variables documented in .env.example.
const env = (typeof import.meta !== 'undefined' && import.meta.env) || {};

export const PREPROD = {
  name: 'preprod',
  // Consumed by setNetworkId(). It must match the network segment of the
  // wallet's addresses (mn_shield-addr_preprod1...).
  networkId: env.VITE_NETWORK_ID ?? 'preprod',
  indexer: env.VITE_INDEXER_URL ?? 'https://indexer.preprod.midnight.network/api/v4/graphql',
  indexerWs: env.VITE_INDEXER_WS_URL ?? 'wss://indexer.preprod.midnight.network/api/v4/graphql/ws',
  node: env.VITE_NODE_URL ?? 'https://rpc.preprod.midnight.network',
  proofServer: env.VITE_PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
  explorer: env.VITE_EXPLORER_URL ?? 'https://explorer.preprod.midnight.network',
};

const HEX64 = /^[0-9a-f]{64}$/i;

const fromQuery = (name) => {
  if (typeof window === 'undefined') return null;
  const value = new URLSearchParams(window.location.search).get(name);
  return value && HEX64.test(value) ? value.toLowerCase() : null;
};

// The Midbid registry on Preprod: the list of auctions the Browse page reads.
// ?registry=<address> overrides it, so a fresh deployment can be tried before
// this default changes. null means no registry yet; auctions still open by
// direct link.
const DEFAULT_REGISTRY_ADDRESS = env.VITE_REGISTRY_ADDRESS || null;
export const REGISTRY_ADDRESS = fromQuery('registry') ?? DEFAULT_REGISTRY_ADDRESS;

export const isContractAddress = (value) => typeof value === 'string' && HEX64.test(value);

// Generated by scripts/provenance.js from the compiled auction's verifier keys.
export { PROVENANCE } from './provenance.js';
