// GENERATED by scripts/provenance.js. Do not edit by hand.
// circuitCommitment = one hash over verifier keys: cancel.verifier, claimWin.verifier, closeUnsold.verifier, placeBid.verifier, settle.verifier
export const PROVENANCE = {
  circuitCommitment: '38c07fcca10121de4a8ec5e1dab327a80160bdbb4b35d7169407a1d3538f7b80',
};
